{% set version = '1.7.7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-refgenome
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/refGenome_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/refGenome/refGenome_{{ version }}.tar.gz
  sha256: e515030cc68f6d2e7570e9a69509a517ab69960a110762ea7e3f5435ec4a48fd

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-doby
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-dbi
    - r-rsqlite
    - r-doby

test:
  commands:
    - $R -e "library('refGenome')"           # [not win]
    - "\"%R%\" -e \"library('refGenome')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=refGenome
  license: GPL-2
  summary: Contains functionalities for importing and managing downloaded genome annotation data
    from 'Ensembl' genome browser (European Bioinformatics Institute, <https://www.ensembl.org>)
    and from 'UCSC' genome browser (University of California, Santa Cruz, <https://genome.ucsc.edu/>)
    and annotation routines for genomic positions and splice site positions.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: refGenome
# Type: Package
# Title: Gene and Splice Site Annotation Using Annotation Data from 'Ensembl' and 'UCSC' Genome Browsers
# Version: 1.7.7
# Date: 2019-04-24
# Authors@R: c(person("Wolfgang", "Kaisers", role=c("aut", "cre"), email="wolfgang.kaisers@gmail.com"))
# Description: Contains functionalities for importing and managing downloaded genome annotation data from 'Ensembl' genome browser (European Bioinformatics Institute, <https://www.ensembl.org>) and from 'UCSC' genome browser (University of California, Santa Cruz, <https://genome.ucsc.edu/>) and annotation routines for genomic positions and splice site positions.
# License: GPL-2
# Depends: methods,doBy,RSQLite
# Imports: DBI
# Collate: refGenome.R geneModel.R
# Packaged: 2019-04-25 19:04:52 UTC; wolfgang
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2019-05-22 18:52:04
# Author: Wolfgang Kaisers [aut, cre]
# Maintainer: Wolfgang Kaisers <wolfgang.kaisers@gmail.com>
